### ISSUE TITLE
Networking key configuration not enabled right away

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#243]
When you visit `AdminNetworkKeys`, you see this:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/3829764/63546541-58c34000-c52a-11e9-83b2-95406a52abb3.png">

The button becomes clickable only after you toggle the checkbox, or open and close the "custom" dialog. It should just be clickable from the start.

(This is when logged in with a mnemonic. Not sure if it repros for ticket login, where key derivation is deterministic.)

**Comment by Fang-** [comment]
The keyfile downloaded after doing this is always the same, too.

**Comment by shrugs** [comment]
hmm, I'm getting odd behavior around the final-form render props: https://github.com/final-form/react-final-form/issues/605

but basically the issue is that

1) we're seeing this flickering
2) react seems to debounce effect running
3) the effect is being run on the invalid state
...
4) final-form stops 'flickering' once an input is made, for some reason, which is why things work after that.

**Comment by shrugs** [comment]
still looking into it
