### ISSUE TITLE
Using mnemonic from urbit hd wallet fails to auto generate networking seed

### ISSUE THREAD

**Issue by iamwillkim** [urbit/bridge#27]
While using the urbit hd wallet master ticket will auto generate a networking seed, using the provided bip39 mnemonic on the paper wallet will not auto generate a networking seed.

**Comment by jtobin** [comment]
@iamwillkim We actually can't auto-generate "appropriate" (i.e. Wallet Generator-compatible) networking seeds from the ownership seed.  The master ticket lets you derive the entire HD wallet, but the ownership seed doesn't -- Wallet Generator-compatible network seeds are derived from the management proxy seed, which can't be derived from the ownership one.

So: if you authenticate with a management proxy seed, and you're really the management proxy for a point, then you should have a network seed auto generated for you when you try to set its keys.  I can verify this works on a Ganache node, at least.

(This is obviously weird from a UX perspective.  We could just propose randomly-generated network seeds for users if we can't otherwise do any better, maybe?)

**Comment by iamwillkim** [comment]
Hm, this may just require better documentation or re-designing the information layout on paper wallets, since the ownership seed + master ticket seem interchangeable, but are not (ownership seed can set networking seed, but cannot derive the networking seed; master ticket can set networking seed, and also derive networking seed).

**Comment by jtobin** [comment]
Going to close this for now as, per wk's comment, it's arguably more of a docs or wallet issue.
