### ISSUE TITLE
Master ticket does not update management proxy change

### ISSUE THREAD

**Issue by sdubyam** [urbit/bridge#368]
Hello,

I own lordev and transferred it to a new wallet (I am going to use lordev to hold some planets and stars).  I changed my management proxy which was successful, and then when I re-downloaded my master ticket, the image file for management proxy was unchanged (did not reflect the new ethereum address).

I'm assuming this is a bug, but do not know the intricacies of these proxies and addresses enough to be sure.

**Comment by Fang-** [comment]
Pretty sure the paper wallet download only gives you keys and proxies as derived from the master ticket directly. If you change the management proxy (so that it can't derive the keys for it) then that won't be reflected in the paper.

I wouldn't call this a bug per se, but the behavior here can certainly be better. Tell you about it, at the very least.

**Comment by sdubyam** [comment]
understood, thank you.
