### ISSUE TITLE
Should update web3 (toWei errors in minified builds only)

### ISSUE THREAD

**Issue by ixv** [urbit/bridge#410]
![image](https://user-images.githubusercontent.com/4741759/76451455-a8fdd480-638c-11ea-888c-aef6e0a54ce3.png)

**Comment by reitraced** [comment]
it seems from what ive heard in discord this happens on all eth transactions right now.

this same kind of issue was also present in the release build on github in v2.3.3

**Comment by reitraced** [comment]
the solution ive been reccomending to people has been to try using v1.4.1 since i dont think azimuth has changed since then and it should work for most stuff

**Comment by vvisigoth** [comment]
That's so weird, I use hosted bridge A LOT (which is latest) and have never
seen this. Would love to hear what tx people are running to see this.
—
~poldec-tonteg
http://urbit.org

**Comment by vvisigoth** [comment]
@reitraced I generally accept invites, transfer, accept transfers (10x/week) with no issues. Have you heard of anyone hitting issues doing that? Or is it only setting/resetting networking keys?

**Comment by reitraced** [comment]
> @reitraced I generally accept invites, transfer, accept transfers (10x/week) with no issues. Have you heard of anyone hitting issues doing that? Or is it only setting/resetting networking keys?

most of the issues ive seen on discord are with reticketing, breaching, or setting keys.

**Comment by Fang-** [comment]
Able to repro this on deployed versions, but not when running locally. Investigating further...

**Comment by vvisigoth** [comment]
I was able to repro on a locally built one.

**Comment by Fang-** [comment]
Good god...

The issue seems to go away when running a non-minimized build. It _does_ occur for production, and locally run builds, but _doesn't_ occur for `npm run pilot` and local builds without minimization.

I'm... gonna go ahead and push a non-minimized build to prod to help resolve this. We should probably be brave and investigate why minimizing the JS borks these functions.

**Comment by Fang-** [comment]
(For those following along: deploy done. Look for `v2.3.4-2` in the bottom right corner of the landing page.)

**Comment by pkova** [comment]
The problem is discussed [here](https://github.com/ethereum/web3.js/issues/1777) and fixed [here](https://github.com/ethereum/web3.js/pull/2793/files). toWei checks the `constructor.name` of the argument to see whether its argument is a BN, which webpack mangles.

In other words just javascript things.

Can't really think of a sane way to fix this without upgrading web3-utils, which is spooky. Couldn't find any webpack options to disable mangling of specific classes either.

**Comment by Fang-** [comment]
Good refs, thanks a bunch @pkova. We should probably look into upgrading web3-utils, then. Hope they went easy with the breaking changes.
