### ISSUE TITLE
Error Report: Objects are not valid as a React child (found: object with keys {ticket, signedTx, rawTx})

### ISSUE THREAD

**Issue by eglaysher** [urbit/bridge#418]
## Context

I was attempting to generate an invite URL in bridge to paste somewhere using a Ledger which holds my management key.

## Error

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bticket%2C%20signedTx%2C%20rawTx%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at mg (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158621:38)
    at z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158715:7)
    at rb (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158781:13)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158898:23
    at S (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:159470:26)
    at mj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:161811:306)
    at jj (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160777:11)
    at Z (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160634:15)
    at $i (https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:160493:16)
    at https://bridge.urbit.org/static/js/2.9ed8dd63.chunk.js:158219:17
```

In Bridge version 2.3.5.

**Comment by eglaysher** [comment]
The actual root cause of this bug is trying to make invite codes with your management key, which the UI lets you do. I was able to build the invite codes with my ownership key.

**Comment by Fang-** [comment]
UI should indeed not let you do this with management keys. Contracts [explicitly disallow](https://github.com/urbit/azimuth/blob/master/contracts/DelegatedSending.sol#L125) anyone but the owner (because this is essentially a spawn proxy-tier operation).

No idea why that fails the way it does though. Should just result in contract errors. Does your ownership key also live on the Ledger?

Regardless, we should add a display check to [this thing](https://github.com/urbit/bridge/blob/6314cefcb49000bbabb5c43bf6f5b1312cd98643/src/views/Point.js#L203-L204).

**Comment by eglaysher** [comment]
There are only management keys on this ledger. But there's a bunch of them, and maybe that's confusing things?

**Comment by Fang-** [comment]
Sounds very unlikely. Bridge always operates exclusively on the address you log in with, it doesn't really know about the existence of anything else. (_Can't_ know, iirc. It can't check assets for all the addresses it didn't receive from the hardware.)
