### ISSUE TITLE
Bridge UI and documentation should make explicit that gifting invites sets the number available and gifts do not compound.

### ISSUE THREAD

**Issue by sivner-figbus** [urbit/bridge#486]
~nibfeb gifted me a pool of 2 invitations. The 2 invitations appeared successfully in Bridge. I did not issue any of them.

He then gifted me a further 5 invitations, for a total of 7. However, when I look in Bridge now, I only see 5 available to me, but I think I should see 7.

~nibfeb is owned and operated by ~somlus-savlev who reports:

`
invites come from the ~somlus bridge which owns ~nibfeb, and the invites are executed under the ~nibfeb ship, selected on the somlus bridge and then heading into the ~nibfeb section. so there might be some ethereum wallet overlap but at least administratively it's coming from nibfeb`

**Comment by Fang-** [comment]
This sounds like confusion around the "set/give invite pool" functionality. Gifting invites like that is _setting the number_ of invites you have available, rather than _incrementing_ it. This is to allow stars to "take back" invites as well.

Other people have reported confusion at this, so we probably need to touch up the copy/ui around this. cc @jyng.

**Comment by sivner-figbus** [comment]
Thank you for the update, appreciated. It clearly wasn't obvious to ~somlus, so if there have been other people confused then the documentation or UI could perhaps do with an update as you note. Updated title to something hopefully more useful.
