### ISSUE TITLE
Unable to access Urbit bridge using Trezor authentication 

### ISSUE THREAD

**Issue by HalifaxShadow** [urbit/bridge#513]
I am unable to authenticate / log into the bridge using my Trezor.  It was working fine previously for accessing my urbit assets.  Once I click yes to confirm the signing authentication on the trezor, it returns me to the log in screen (attached) with the "Authenticate" button grayed out.  No error code is given.

![Screenshot from 2020-08-07 09-17-56](https://user-images.githubusercontent.com/64690771/89598250-e9577500-d88e-11ea-9389-92c966b8d351.png)

Add'l details:
Trezor Model T
Firmware: 2.3.2
Problem replicated on following browsers: Chrome, Chromium, Vivaldi, Brave, Firefox
OS: tried in both Ubuntu 18.06 and Windows 10 on 2 different machines

Also, it is worth noting the Trezor bridge itself seems to be working (I can access my wallet without a hitch on trezor.io).

**Comment by HalifaxShadow** [comment]
I have tried to use the local bridge and actually got an error message when I did, "Failed to authenticate with your Trezor."

screenshot attached

(https://user-images.githubusercontent.com/64690771/89609143-950dbe80-d8a9-11ea-9e5e-f164ca872469.png)

**Comment by Fang-** [comment]
Thanks for the detailed report! I only have an old Trezor around, not a model T, but I assume nothing relevant changed between the two. I'll try this out and see what's up with it.

**Comment by HalifaxShadow** [comment]
> Thanks for the detailed report! I only have an old Trezor around, not a model T, but I assume nothing relevant changed between the two. I'll try this out and see what's up with it.

Thank you!

**Comment by HalifaxShadow** [comment]
All, based on advice from urbit-help: "One posisble workaround might be to use metamask to talk to your trezor"

Once I added the Trezor into my metamask, I was able to log into the bridge using metamask.  I feel like this is useful information for solving this bug.

**Comment by JohnELester** [comment]
I came here to say that I always use my Trezor via Metamask to successfully interact with bridge.   Glad that advice made its way here!

**Comment by zalberico** [comment]
I also hit this bug, some addition context - this appears in the web console:
```
The web console has this error:
Uncaught (in promise) 
Error: Forbidden key path
    _callee2$ trezor.js:46
    tryCatch runtime.js:45
    invoke runtime.js:265
    method runtime.js:98
```

**Comment by syzygyzer** [comment]
Ran into this today.

Confirmed that the bug still exists for Model T firmware v2.3.3

Downgrading to v2.3.0 allows Bridge to work fine with the Model T natively, without the use of Metamask.

**Comment by Fang-** [comment]
@HalifaxShadow Logging in with my Trezor One, I got the "Failed to authenticate with your Trezor" at first. Turns out my adblock was preventing Bridge from loading in some remote resources that the trezor-connect wanted access to. Unblocking those resolved that issue, and allowed me to log in as normal.


Thanks for the research and references, @zalberico. trezor/trezor-firmware#1044 seems absolutely crazy to me. Trezor isn't a standards organization, is it? Who are they to enforce what keys their users can and cannot derive?

Regardless, we do by default use the derivation path structure that they [consider valid](https://github.com/trezor/trezor-firmware/blob/master/docs/misc/coins-bip44-paths.md) for Ethereum accounts:

https://github.com/urbit/bridge/blob/a751ef0312a15b4a0188abe923ab64abc1794c7d/src/lib/trezor.js#L4

So if you're just selecting an account, it shouldn't be telling you "forbidden keypath". If it does, something is wrong somewhere. For the custom path situation, I'm afraid you're on your own...

Just in case it's relevant, I went and upgraded the trezor-connect dependency to the latest version. Bridge v2.5.8 is live now and should be using it. Let me know if anything behaves differently.


> I'm a little hesitant because I don't know what these paths mean and I don't want to mess up receiving my star.

You can also just not bother with the custom path, and select an account from the dropdown instead. (;  
As long as you control the address you give/gave for receiving the star, you'll be fine. Using a custom path would be perfectly valid, except Trezor Corp might give you pain for it.

**Comment by zalberico** [comment]
Thanks, for clarity I got that forbidden key error *without the custom key path*.

I also got it with the custom key path too.

Metamask workaround worked, but I can try again to see if your update fixed things for direct trezor access.
