### ISSUE TITLE
Putting in an address with invalid checksum crashes the app

### ISSUE THREAD

**Issue by Fang-** [urbit/bridge#52]
You can reproduce this by copy-pasting your logged-in-as address into an address field, and then changing one of the letters to/from capital.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/3829764/51089675-1df06280-1726-11e9-9350-7508bd5d0490.png">

**Comment by c-johnson** [comment]
Yeah, azimuth.ecliptic throws exceptions that crash the app when in development mode. I think this is by design?

I've lowercased the address input before we submit it to ecliptic; that should handle this particular error, I think other conceivable errors should be handled in the validator function. 

We could try wrapping these in a try/catch to prevent app crashing; not sure if @jtobin has a better idea for how we should handle these exceptions.
