### ISSUE TITLE
signing function mismatch between Metamask / ETH toolkit

### ISSUE THREAD

**Issue by forfel-norfel** [urbit/bridge#549]
Not sure if it's a limitation of the app, but even some text that can be copied and pasted into a file would be very helpful here.

**Comment by forfel-norfel** [comment]
I just tried watching the console on my Mac as I was trying to download the network key in the app on my phone and I saw this error:

`-canOpenURL: failed for URL: "blob:https://bridge.urbit.org/[removed uuid that was here]" - error: "This app is not allowed to query for scheme blob"`

**Comment by Fang-** [comment]
Ah, so the keyfile is available, but your browser isn't letting you download it. Interesting. We can probably add a text-only option for this.

**Comment by rivmud-fabwen** [comment]
I ran into this issue when using the MetaMask browser extension on desktop Vivaldi (Chromium).  Clicking on the "download keyfile" button doesn't do anything when I'm logged in with MetaMask.  The download works fine if I log in with my master ticket though.

**Comment by rivmud-fabwen** [comment]
@tomholford There's no console output or network request made when I click on the button.  
My cursor does change to reflect that I'm mousing over a button, so it at least recognizes that it's a button I think.

**Comment by tomholford** [comment]
I have been digging into this for some time, getting closer to finding the root cause.

 So far I have ruled out several issues (revision off-by-one, Metamask Ethereum Provider API breaking changes). 

The issue is that `keys.js#attemptNetworkSeedDerivation` is returning different seeds for the same mnemonic (Recovery Phrase vs. Metamask login flows). It appears that the reason for this is that different auth tokens are being derived, which is definitely incorrect behavior (given the same mnemonic and thus the same private key, the auth tokens should be identical).

Continuing to investigate ...

**Comment by tomholford** [comment]
An update on this:

Confirming that the root cause is due to [this commit](https://github.com/urbit/bridge/commit/003c08396edb548527e8ffd56218fca90d7f2d8b#diff-ea521a1b242dfb1472db45d56b3f869a255d301f033f3c2d0aeb504c316c24bcL17), which introduced a discrepancy between how auth tokens are generated between custodial and non-custodial wallets. Specifically, [per the docs](https://wallet-docs.brave.com/ethereum/use-cases/signing-data/#personal_sign) for `personal_sign`, `keccak256` is used by Ethereum Providers to sign a message.

When I first joined the Bridge project and had little insight into how things worked, I instead used the subtly different `sha256` for the default auth token case (i.e, for master tickets and mnemonics). As such, for roughly the past 6 months, any actions performed in Bridge (generating invites, setting keys, etc) using these login methods were with a logically incorrect auth token.

Per out-of-band conversation with @Fang- , we have come up with both a fix and a mitigation strategy for users affected by this issue:

- first, the default auth token derivation will be restored to match the same implementation as Ethereum Providers. This will resolve this issue going forward
- second, an optional "Legacy Compatibility" checkbox will be added to custodial login flows; when this is enabled, the auth token will be derived using  `sha256` instead of `keccak256`. This will enable users who have set keys in the past ~6 months to deterministically re-derive them in Bridge.
