### ISSUE TITLE
Consider removing 'set transfer proxy' action from Point view

### ISSUE THREAD

**Issue by gavinpatkinson** [urbit/bridge#55]
(Original title: **Setting a transfer proxy asks the user to to accept an incoming transfer of a ship.**)

Not sure if this is intended behavior, but it caught me by surprise and surprises are bad in Bridge.

**Comment by jtobin** [comment]
Coming back to this again during issue triage: I think the 'set transfer proxy' action should just be removed.  Instead of smart contracts asking to be set as a transfer proxy, they should ask to be transferred the ship.  The two are, after all, the same thing. 😄 

I don't see any other satisfying way to resolve this -- there's no way to semantically distinguish a ship with a set transfer proxy from a ship being transferred.

**Comment by Fang-** [comment]
> Instead of smart contracts asking to be set as a transfer proxy, they should ask to be transferred the ship. The two are, after all, the same thing.

This is wrong though!  
In the "I transfer a point to the contract" case, the contract doesn't know it owns the thing until you explicitly tell it so (which can be done through ERC721's `safeTransfer` also).  
In the "I tell the contract it can now transfer a point to itself" case, you already told the contract, so it knows, and you have the guarantee that the contract *actually* has functionality for dealing with points.

Reading the issue OP, it sounds like "setting *any* transfer proxy causes *me* to get a notification". Is that what this is? That's obviously incorrect.

> there's no way to semantically distinguish a ship with a set transfer proxy from a ship being transferred.

But why distinguish? Those are identical cases. Transferring is what the transfer proxy is for. "Tell [transfer proxy address] to complete the transfer" holds as sound instructions for both the to-person and to-contract cases.

**Comment by jtobin** [comment]
> In the "I transfer a point to the contract" case, the contract doesn't know it owns the thing until you explicitly tell it so (which can be done through ERC721's `safeTransfer` also).
>
> In the "I tell the contract it can now transfer a point to itself" case, you already told the contract, so it knows, and you have the guarantee that the contract _actually_ has functionality for dealing with points.
>
> [..]
>
> But why distinguish? Those are identical cases. Transferring is what the transfer proxy is for. "Tell [transfer proxy address] to complete the transfer" holds as sound instructions for both the to-person and to-contract cases.

What I mean is that I recommend that we make the only visible option *in Bridge* to be 'Transfer', rather than 'Set Transfer Proxy', which, as you point out, does the exact same thing as 'Transfer'. 
 Alternatively we could remove 'Transfer', but it seems like 'Set Transfer Proxy' is somewhat more obfuscated.  Basically: having two actions that do the same thing seems sort of pointless, if benign.

> Reading the issue OP, it sounds like "setting _any_ transfer proxy causes _me_ to get a notification". Is that what this is? That's obviously incorrect.

Now that I think on this: I presume Gav originally set a transfer proxy to himself for testing, which will then enable the 'Accept incoming transfer' action in the Point view, and also populate the 'Incoming Transfers' list on the Points view, for a ship he already owns.  So probably that's the real issue, and the 'Set Transfer Proxy' vs 'Transfer' business is a red herring. 😄

**Comment by Fang-** [comment]
Ohhh, I see. That makes a lot more sense! I'm all for removing "set transfer proxy" then, as long as the "transfer" page mentions that "The recipient will need to accept the transfer to complete it."

**Comment by jtobin** [comment]
Yeah I'll leave this open for `$FUTURE_BRIDGE_DEVELOPER` to resolve, in any case, but it seems like it's not much of an issue after all.

**Comment by urbitalex** [comment]
@Fang- what else needs to be done here?

**Comment by Fang-** [comment]
I think this is resolved in @c-johnson's PR as per [this commit](https://github.com/urbit/bridge/commit/34155b2335a37a544cf16a300234e53839744c17). The copy also seems fine for now.
