### ISSUE TITLE
A management mnemonic cannot create invite codes [roller]

### ISSUE THREAD

**Issue by tomholford** [urbit/bridge#633]
While testing #621, @yosoyubik and I encountered an issue with generating invite codes [[context](https://github.com/urbit/bridge/pull/621#discussion_r714580960)]. Specifically, logging in with the development ETH private key (that owns the points on testnet) allows one to generate new invite codes. When logging in with the management mnemonic from `DEVELOPMENT.md`, one is not able to create said codes. This behavior has been observed on `roller` branch, yet to be determined if also on `master`.

*To reproduce:*
1. Start Bridge locally with `npm run pilot-l2`
2. Log in to Bridge with the mnemonic
3. Click the envelope and attempt to generate an invite code
4. The UI does not indicate success or failure, but check the network tab in the browser devtools to see that API requests to the roller are stopping after the `spawn` request:

![image](https://user-images.githubusercontent.com/16504501/134546608-435d6e91-a783-4bb2-b18d-3420d304d30d.png)

Open questions:
- Should there be a difference in behavior when logging into Bridge with a management mnemonic?
- If so, how should we inform the user?

**Comment by Fang-** [comment]
Pretty sure this is juist a UI-side issue, because:

> Should there be a difference in behavior when logging into Bridge with a management mnemonic?

Yes. The management keys for a star do not have the ability to spawn planets. Only the ownership address and spawn proxy can do this.  
(Additionally, in the "planet is sending an invite" case on current livenet, this goes through the DelegatedSending contract, which only lets planet _owners_ (not any proxies) send planets on behalf of the star.)

> If so, how should we inform the user?

I believe behavior for the current invite flow is to just not show the option in the UI? But certainly a greying-out and "you can do this if you log in with x" seems nicer.

**Comment by lukestiles** [comment]
Closing as this is tracked in the design ticket, which references this issue.
