### ISSUE TITLE
L2: incorrect display after setting spawn proxy to L2

### ISSUE THREAD

**Issue by nerveharp** [urbit/bridge#874]
Bridge unreliably detected a L1 star with its proxy set to L2. The user queried the back-end and got `"dominion": "spawn"`. They suspect there may be some type coercion when calculating the tx nonce (needs to be a string, not a number).

Possible fix: web+urbitgraph://group/~wolref-podlex/next-pki/graph/~wolref-podlex/general-1012/170141184505442700329412495133787553792

**Comment by drbeefsupreme** [comment]
Confirming that this is still an issue. The hack in the link does fix it - I put it in a commit for easy viewing:

https://github.com/urbit/bridge/commit/7f1597155f0a4117dca29fa1acac01f537d23f95

I'm guessing this isn't really the right way to do things though, and I don't otherwise have any familiarity with the codebase, so someone else will have to do the PR.

**Comment by nerveharp** [comment]
@tomholford to follow up with @ryjm and @yosoyubik.
